# Generated by Django 4.2.30 on 2026-07-27 15:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_tag', models.CharField(help_text='Business asset ID shown on labels / QR payloads.', max_length=64, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('brand', models.CharField(blank=True, default='', max_length=80)),
                ('model', models.CharField(blank=True, default='', max_length=80)),
                ('serial_number', models.CharField(max_length=120, unique=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('warranty_expiry', models.DateField(blank=True, db_index=True, null=True)),
                ('qr_code', models.ImageField(blank=True, help_text='Generated QR image file (local media).', null=True, upload_to='qr_codes/')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('REQUESTED', 'Requested'), ('ALLOCATED', 'Allocated'), ('MAINTENANCE', 'Maintenance'), ('RETIRED', 'Retired'), ('LOST', 'Lost')], db_index=True, default='AVAILABLE', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='assets/')),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'asset',
                'verbose_name_plural': 'assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'asset category',
                'verbose_name_plural': 'asset categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('contact_person', models.CharField(blank=True, default='', max_length=120)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('address', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'vendor',
                'verbose_name_plural': 'vendors',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'name'], name='idx_vendor_active_name')],
            },
        ),
        migrations.CreateModel(
            name='AssetAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_at', models.DateTimeField(db_index=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RETURNED', 'Returned'), ('LOST', 'Lost')], db_index=True, default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='assets.asset')),
            ],
            options={
                'verbose_name': 'asset assignment',
                'verbose_name_plural': 'asset assignments',
                'ordering': ['-assigned_at'],
            },
        ),
    ]
