# Generated by Django 4.2.30 on 2026-07-27 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_assignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assetcategory'),
        ),
        migrations.AddField(
            model_name='asset',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.vendor'),
        ),
        migrations.AddIndex(
            model_name='assetassignment',
            index=models.Index(fields=['employee', 'status'], name='idx_assign_emp_status'),
        ),
        migrations.AddIndex(
            model_name='assetassignment',
            index=models.Index(fields=['asset', 'status'], name='idx_assign_asset_status'),
        ),
        migrations.AddConstraint(
            model_name='assetassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('asset',), name='uq_asset_one_active_assignment'),
        ),
        migrations.AddConstraint(
            model_name='assetassignment',
            constraint=models.CheckConstraint(check=models.Q(('returned_at__isnull', True), ('returned_at__gte', models.F('assigned_at')), _connector='OR'), name='chk_assign_return_after_assign'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['status', 'category'], name='idx_asset_status_cat'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['brand', 'model'], name='idx_asset_brand_model'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['vendor', 'status'], name='idx_asset_vendor_status'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(check=models.Q(('purchase_cost__isnull', True), ('purchase_cost__gte', 0), _connector='OR'), name='chk_asset_purchase_cost_nonneg'),
        ),
    ]
