# Generated by Django 4.2.30 on 2026-07-27 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('ASSIGN', 'Assign'), ('RETURN', 'Return'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('LOGIN', 'Login'), ('STATUS_CHANGE', 'Status Change')], db_index=True, max_length=32)),
                ('entity_type', models.CharField(db_index=True, help_text="Model label, e.g. 'assets.Asset'.", max_length=64)),
                ('entity_id', models.CharField(db_index=True, help_text='Primary key of the target entity as string.', max_length=64)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Before/after snapshot or field diffs.')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed the action; null for system jobs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'audit log',
                'verbose_name_plural': 'audit logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='idx_audit_entity'), models.Index(fields=['actor', 'created_at'], name='idx_audit_actor_created'), models.Index(fields=['action', 'created_at'], name='idx_audit_action_created')],
            },
        ),
    ]
