# Generated by Django 4.2.30 on 2026-07-27 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrequest',
            name='asset',
            field=models.ForeignKey(blank=True, help_text='Optional specific asset being requested.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Requested category when no specific asset is chosen.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='assets.assetcategory'),
        ),
    ]
