# Generated by Django 4.2.30 on 2026-07-27 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvals', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_requests', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='approval',
            name='approver',
            field=models.ForeignKey(limit_choices_to={'role__in': ['MANAGER', 'ADMIN']}, on_delete=django.db.models.deletion.PROTECT, related_name='approvals_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approval',
            name='asset_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='approvals.assetrequest'),
        ),
        migrations.AddIndex(
            model_name='assetrequest',
            index=models.Index(fields=['status', 'priority', 'created_at'], name='idx_req_status_prio_created'),
        ),
        migrations.AddIndex(
            model_name='assetrequest',
            index=models.Index(fields=['requested_by', 'status'], name='idx_req_employee_status'),
        ),
        migrations.AddConstraint(
            model_name='assetrequest',
            constraint=models.CheckConstraint(check=models.Q(('category__isnull', False), ('asset__isnull', False), _connector='OR'), name='chk_request_has_category_or_asset'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['approver', 'decision'], name='idx_approval_approver_decision'),
        ),
        migrations.AddConstraint(
            model_name='approval',
            constraint=models.UniqueConstraint(fields=('asset_request', 'step'), name='uq_approval_request_step'),
        ),
        migrations.AddConstraint(
            model_name='approval',
            constraint=models.CheckConstraint(check=models.Q(('step__gte', 1)), name='chk_approval_step_positive'),
        ),
    ]
