# Generated by Django 4.2.30 on 2026-07-28 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('approvals', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrequest',
            name='assignment',
            field=models.ForeignKey(blank=True, help_text='Assignment created when the request was fulfilled.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_requests', to='assets.assetassignment'),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='fulfilled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='fulfilled_by',
            field=models.ForeignKey(blank=True, help_text='IT / Admin user who allocated the asset.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_asset_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='approval',
            name='approver',
            field=models.ForeignKey(blank=True, help_text='Assigned manager/admin. Null until a department manager is configured.', limit_choices_to={'role__in': ['MANAGER', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approvals_made', to=settings.AUTH_USER_MODEL),
        ),
    ]
