# Generated by Django 4.2.30 on 2026-07-27 15:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('issue_description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='OPEN', max_length=20)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='assets.asset')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='IT staff responsible for the ticket.', limit_choices_to={'role__in': ['IT_TEAM', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_maintenance', to='employees.employee')),
            ],
            options={
                'verbose_name': 'maintenance record',
                'verbose_name_plural': 'maintenance records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['asset', 'status'], name='idx_maint_asset_status'), models.Index(fields=['assigned_to', 'status'], name='idx_maint_assignee_status'), models.Index(fields=['reported_by', 'created_at'], name='idx_maint_reporter_created')],
            },
        ),
        migrations.AddConstraint(
            model_name='maintenancerecord',
            constraint=models.CheckConstraint(check=models.Q(('cost__isnull', True), ('cost__gte', 0), _connector='OR'), name='chk_maint_cost_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='maintenancerecord',
            constraint=models.CheckConstraint(check=models.Q(('completed_at__isnull', True), ('started_at__isnull', True), ('completed_at__gte', models.F('started_at')), _connector='OR'), name='chk_maint_completed_after_start'),
        ),
    ]
